# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client/**'
      - 'server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'client/**'
      - 'server/**'

jobs:
  build-client:
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'client/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout client code
      uses: actions/checkout@v4
      with:
        path: client

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build client
      run: npm run build

    - name: Test client
      run: npm test

    - name: Deploy to Apache
      env:
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        echo "$VPS_PASSWORD" | sshpass ssh $VPS_USERNAME@45.77.18.47 "rm -rf /var/www/html/*"
        echo "$VPS_PASSWORD" | sshpass scp -r ./client/dist/* $VPS_USERNAME@45.77.18.47:/var/www/html/

  build-server:
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'server/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout server code
      uses: actions/checkout@v4
      with:
        path: server

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build server
      run: npm run build

    - name: Test server
      run: npm test

    - name: Deploy and start server with PM2
      env:
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        echo "$VPS_PASSWORD" | sshpass ssh $VPS_USERNAME@45.77.18.47 "cd /path/to/your/server && npm install && pm2 start src/app.js"
