# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: [ "server" ]
  pull_request:
    branches: [ "server" ]
    
jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout server code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # - name: Copy build file to server
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.VPS_IP_ADDRESS }}
    #     username: ${{ secrets.VPS_USERNAME }}
    #     key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
    #     port: 80
    #     source: "./*"
    #     target: /var/www

    # - name: Deploy on Apache
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.VPS_IP_ADDRESS }}
    #     username: ${{ secrets.VPS_USERNAME }}
    #     key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
    #     port: 80
    #     script: |
    #       whoami
    #       rm -rf /var/www/html/*

    - name: Start server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_IP_ADDRESS }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        port: 80
        script: |
          npm install
          pm2 start src/app.js
